stages:
  # Bước 1: Nạp dữ liệu thô từ Hugging Face
  data_ingestion:
    cmd: python src/data_ingestion.py --output data/raw
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/medical_chatbot_raw.csv

  # Bước 2: Tiền xử lý (Format ChatML & Split dữ liệu)
  data_preprocessing:
    cmd: python src/data_preprocessing.py --input data/raw/medical_chatbot_raw.csv --output data/processed
    deps:
      - data/raw/medical_chatbot_raw.csv
      - src/data_preprocessing.py
    outs:
      - data/processed/train.jsonl
      - data/processed/val.jsonl

  # Bước 3: Xử lý dữ liệu số (Tokenization)
  data_processing:
    cmd: python src/data_processing.py --input_dir data/processed --output_dir data/tokenized --model_id Qwen/Qwen2.5-0.5B-Instruct
    deps:
      - data/processed/train.jsonl
      - data/processed/val.jsonl
      - src/data_processing.py
    outs:
      - data/tokenized/train
      - data/tokenized/val

  # Bước 4: Xây dựng và Huấn luyện mô hình (3 Epochs)
  model_building:
    # Lưu ý: Thêm export PYTHONPATH để tránh lỗi ModuleNotFoundError trên MINGW64
    cmd: python src/model_building.py --input_dir data/tokenized --output_dir models/qwen-medical-finetuned
    deps:
      - data/tokenized/
      - src/model_building.py
      - src/data_processing.py
    outs:
      - models/qwen-medical-finetuned/final_adapter

  # Bước 5: Thêm RAG
  model_rag:
    cmd: python src/model_RAG.py --model_base_id Qwen/Qwen2.5-0.5B-Instruct --adapter_path models/qwen-medical-finetuned/final_adapter --vectorstore_path data/rag_vectorstore
    deps:
      - models/qwen-medical-finetuned/final_adapter
      - src/model_RAG.py
    outs:
      - data/rag_vectorstore

  # Bước 6: Đánh giá mô hình 
  model_evaluating:
    cmd: python src/model_evaluating.py --val_file data/processed/val.jsonl --output_metrics metrics.json --vectorstore_path data/rag_vectorstore
    deps:
      - data/processed/val.jsonl
      - src/model_evaluating.py
      - src/model_RAG.py
      - models/qwen-medical-finetuned/final_adapter
      - data/rag_vectorstore
    metrics:
      - metrics.json: # DVC sẽ theo dõi file này như một report
          cache: false